owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  sassy:
    kind: system
    host: sassy.caltech.edu

pipeline:
  # TODO: Run all in parallel since they don't depend on each other
  # sequence:
  #   - [baro-43-clima, baro-63-clima, amip-clima]
  stages:
    baro-43-clima-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys-clima.sh
      sbatch_options:
        - --gpus=1
        - --time=30
      args:
        - nsys-outputs/baroclinic-wave-moist-43
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/baroclinic-wave-moist-43.nsys-rep
    baro-63-clima-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys-clima.sh
      sbatch_options:
        - --gpus=1
        - --time=60
      args:
        - nsys-outputs/baroclinic-wave-moist-63
        - config/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - config/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/baroclinic-wave-moist-63.nsys-rep
    amip-clima-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys-clima.sh
      sbatch_options:
        - --gpus=1
        - --time=240
      args:
        - nsys-outputs/amip-target-edonly-63
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - config/amip_target_edonly.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/perf/common.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - config/amip_target_edonly.yml
        - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/amip-target-edonly-63.nsys-rep
    amip-clima-ncu:
      kind: sbatch
      environment: clima
      script_path: scripts/run-ncu-clima.sh
      sbatch_options:
        - --gpus=1
        - --time=240
      args:
        - ncu-outputs/amip-target-edonly-63
        - --config ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - --config config/amip_target_edonly.yml
        - --kernel-name copyto_stencil_kernel_
        - --launch-skip 0
        - --launch-count 20
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - config/amip_target_edonly.yml
        - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - ncu-outputs/amip-target-edonly-63.ncu-rep
    amip-ncu-update-jacobian:
      kind: sbatch
      environment: clima
      script_path: scripts/run-ncu-amip-update-jacobian.sh
      sbatch_options:
        - --gpus=1
        - --time=240
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/perf/common.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - config/amip_target_edonly.yml
        - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - ncu-outputs/amip-update-jacobian-kernel.ncu-rep
