owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  sassy:
    kind: system
    host: sassy.caltech.edu

pipeline:
  stages: {}
