owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  sassy:
    kind: system
    host: sassy.caltech.edu

  py:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"
pipeline:
  stages:
    baseline-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/nsys/baseline
        - ClimaCoupler.jl/experiments/ClimaEarth
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
        - ClimaCoupler.jl/experiments/ClimaEarth/components
      outputs:
        - results/nsys/baseline.nsys-rep
    baseline-nsys-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline.nsys-rep -t sqlite
        -o results/nsys/baseline.sqlite
      inputs:
        - results/nsys/baseline.nsys-rep
      outputs:
        - results/nsys/baseline.sqlite
