owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  sassy:
    kind: system
    host: sassy.caltech.edu
  py:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"

pipeline:
  stages:
    baseline-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/nsys/baseline
        - ClimaCoupler.jl/experiments/ClimaEarth
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
        - ClimaCoupler.jl/experiments/ClimaEarth/components
        - ClimaCore.jl/ext
        - ClimaCore.jl/src
        - ClimaCore.jl/lib
      outputs:
        - results/nsys/baseline.nsys-rep
    baseline-nsys-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/baseline.nsys-rep -t sqlite
        -o results/nsys/baseline.sqlite
      inputs:
        - results/nsys/baseline.nsys-rep
      outputs:
        - results/nsys/baseline.sqlite
    summarize-baseline-nsys:
      kind: python-script
      environment: py
      script_path: scripts/summary-from-nsys.py
      args:
        - results/nsys/baseline.sqlite
      inputs:
        - results/nsys/baseline.sqlite
      outputs:
        - path: results/nsys/baseline.summary.json
          storage: git
    mod-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/nsys/mod
        - ClimaCoupler.jl-mod/experiments/ClimaEarth
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-mod/src
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
        - ClimaCoupler.jl-mod/experiments/ClimaEarth/components
        - ClimaCore.jl-mod/ext
        - ClimaCore.jl-mod/src
        - ClimaCore.jl-mod/lib
        - ClimaAtmos.jl-mod/src
      outputs:
        - results/nsys/mod.nsys-rep
    mod-nsys-to-sqlite:
      kind: shell-command
      environment: _system
      command: nsys export results/nsys/mod.nsys-rep -t sqlite
        -o results/nsys/mod.sqlite
      inputs:
        - results/nsys/mod.nsys-rep
      outputs:
        - results/nsys/mod.sqlite
    summarize:
      kind: python-script
      environment: py
      script_path: scripts/summarize.py
      inputs:
        - results/nsys/baseline.sqlite
        - results/nsys/mod.sqlite
      outputs:
        - path: results/summary.json
          storage: git
    baseline-ncu:
      kind: sbatch
      environment: clima
      script_path: scripts/run-ncu.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/ncu/baseline
        - --kernel-name
        - run_field_matrix_solver__FILE_ClimaCore_jl_src_MatrixFields_field_matrix_solver_jl_L354
        - --project
        - ClimaCoupler.jl/experiments/ClimaEarth
        - --config
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - --launch-count
        - "6"
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
        - ClimaCoupler.jl/experiments/ClimaEarth/components
        - ClimaCore.jl/ext
        - ClimaCore.jl/src
        - ClimaCore.jl/lib
      outputs:
        - results/ncu/baseline.ncu-rep
    baseline-ncu-details-csv:
      kind: shell-command
      environment: _system
      command: ncu --csv -i results/ncu/baseline.ncu-rep --page details
        --log-file results/ncu/baseline-details.csv
      inputs:
        - results/ncu/baseline.ncu-rep
      outputs:
        - path: results/ncu/baseline-details.csv
          storage: git
