owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

machines: {}

environments:
  main:
    kind: julia
    path: Project.toml
  clima-ssh:
    kind: ssh
    host: clima.gps.caltech.edu
    user: $CALTECH_USERNAME
    wdir: ~/calkit/clima-gpu-profiling
    load_modules:
      - TODO
    sync_method: repo
  clima-main:
    kind: composite
    env1: clima
    env2: main
  sassy:
    kind: ssh
    host: sassy.caltech.edu
    user: $CALTECH_USERNAME
    wdir: ~/calkit/clima-gpu-profiling
    sync_method: repo
  sassy-main:
    kind: composite
    env1: sassy
    env2: main
  clima:
    kind: slurm

env_vars:
  CLIMACOMMS_DEVICE: CUDA

pipeline:
  sequence:
    # Run all in parallel since they don't depend on each other
    - [baro-43-clima, baro-63-clima, amip-clima]
  stages:
    baro-43-clima:
      kind: sbatch-script
      script_path: scripts/run-slurm.sh
      host: clima.gps.caltech.edu
      gpus: 1
      time: 240
      args:
        - nsys-outputs/baroclinic-wave-moist-43
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/baroclinic-wave-moist-43.nsys-rep
    baro-63-clima:
      kind: sbatch-script
      script_path: scripts/run-slurm.sh
      host: clima.gps.caltech.edu
      gpus: 1
      time: 240
      args:
        - nsys-outputs/baroclinic-wave-moist-63
        - config/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - config/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/baroclinic-wave-moist-63.nsys-rep
    amip-clima:
      kind: sbatch-script
      script_path: scripts/run-slurm.sh
      host: clima.gps.caltech.edu
      gpus: 1
      args:
        - nsys-outputs/amip-target-edonly-63
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/longrun_configs/amip_target_edonly.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/longrun_configs/amip_target_edonly.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/amip-target-edonly-63.nsys-rep
