owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu
  sassy:
    kind: system
    host: sassy.caltech.edu
  py:
    path: requirements.txt
    kind: uv-venv
    prefix: .venv
    python: "3.13"

pipeline:
  stages:
    baseline-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/nsys/baseline
        - ClimaCoupler.jl/experiments/AMIP
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl/experiments/AMIP/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/AMIP/code_loading.jl
        - ClimaCore.jl/ext
        - ClimaCore.jl/src
        - ClimaCore.jl/lib
      outputs:
        - results/nsys/baseline.nsys-rep
        - results/nsys/baseline.sqlite
    mod-nsys:
      kind: sbatch
      environment: clima
      script_path: scripts/run-nsys.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/nsys/mod
        - ClimaCoupler.jl-mod/experiments/AMIP
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-mod/src
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl-mod/experiments/AMIP/Manifest-v1.11.toml
        - ClimaCoupler.jl-mod/experiments/AMIP/code_loading.jl
        - ClimaCore.jl-mod/ext
        - ClimaCore.jl-mod/src
        - ClimaCore.jl-mod/lib
        - ClimaAtmos.jl-mod/src
        - CloudMicrophysics.jl-mod/src
      outputs:
        - results/nsys/mod.nsys-rep
        - results/nsys/mod.sqlite
    baseline-ncu:
      kind: sbatch
      environment: clima
      script_path: scripts/run-ncu.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/ncu/baseline
        - --kernel-name
        - set_microphysics_tendency_cache__FILE_ClimaAtmos_jl_src_cache_microphysics_cache_jl_L1021
        - --project
        - ClimaCoupler.jl/experiments/AMIP
        - --config
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - --launch-count
        - "6"
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl/experiments/AMIP/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/AMIP/code_loading.jl
        - ClimaCore.jl/ext
        - ClimaCore.jl/src
        - ClimaCore.jl/lib
        - ClimaAtmos.jl/src
      outputs:
        - results/ncu/baseline.ncu-rep
        - path: results/ncu/baseline-details.csv
          storage: git
    mod-ncu:
      kind: sbatch
      environment: clima
      script_path: scripts/run-ncu.sh
      sbatch_options:
        - --gpus=1
        - --time=120
      args:
        - results/ncu/mod
        - --kernel-name
        - set_microphysics_tendency_cache__FILE_ClimaAtmos_jl_mod_src_cache_microphysics_cache_jl_L1021
        - --project
        - ClimaCoupler.jl-mod/experiments/AMIP
        - --config
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - --launch-count
        - "6"
      inputs:
        - scripts/run.jl
        - ClimaCoupler.jl-mod/src
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl-mod/experiments/AMIP/Manifest-v1.11.toml
        - ClimaCoupler.jl-mod/experiments/AMIP/code_loading.jl
        - ClimaCore.jl-mod/ext
        - ClimaCore.jl-mod/src
        - ClimaCore.jl-mod/lib
        - ClimaAtmos.jl-mod/src
        - CloudMicrophysics.jl-mod/src
      outputs:
        - results/ncu/mod.ncu-rep
        - path: results/ncu/mod-details.csv
          storage: git
    # A stage to run a bit longer for a better picture of performance differences
    amip-baseline:
      kind: sbatch
      environment: clima
      script_path: scripts/run-julia-script.sh
      sbatch_options:
        - --gpus=1
        - --time=240
      args:
        - --project=ClimaCoupler.jl/experiments/AMIP
        - ClimaCoupler.jl/experiments/AMIP/run_simulation.jl
        - --config_file
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - --job_id
        - gpu_amip_progedmf_1M_land_he16_baseline
      inputs:
        - ClimaCoupler.jl/experiments/AMIP/run_simulation.jl
        - ClimaCoupler.jl/src
        - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl/experiments/AMIP/Manifest-v1.11.toml
        - ClimaCoupler.jl/experiments/AMIP/code_loading.jl
        - ClimaCore.jl/ext
        - ClimaCore.jl/src
        - ClimaCore.jl/lib
        - ClimaAtmos.jl/src
        - ClimaAtmos.jl/toml
    amip-mod:
      kind: sbatch
      environment: clima
      script_path: scripts/run-julia-script.sh
      sbatch_options:
        - --gpus=1
        - --time=240
      args:
        - --project=ClimaCoupler.jl-mod/experiments/AMIP
        - ClimaCoupler.jl-mod/experiments/AMIP/run_simulation.jl
        - --config_file
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - --job_id
        - gpu_amip_progedmf_1M_land_he16_mod
      inputs:
        - ClimaCoupler.jl-mod/experiments/AMIP/run_simulation.jl
        - ClimaCoupler.jl-mod/src
        - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
        - ClimaCoupler.jl-mod/experiments/AMIP/Manifest-v1.11.toml
        - ClimaCoupler.jl-mod/experiments/AMIP/code_loading.jl
        - ClimaCore.jl-mod/ext
        - ClimaCore.jl-mod/src
        - ClimaCore.jl-mod/lib
        - ClimaAtmos.jl-mod/src
        - ClimaAtmos.jl-mod/toml
        - CloudMicrophysics.jl-mod/src
    summarize:
      kind: python-script
      environment: py
      script_path: scripts/summarize.py
      inputs:
        - results/nsys/baseline.sqlite
        - results/nsys/mod.sqlite
        - from_stage_outputs: amip-baseline
        - from_stage_outputs: amip-mod
      outputs:
        - path: results/summary.json
          storage: git
    compare-kernels:
      kind: jupyter-notebook
      notebook_path: notebooks/compare-kernels.ipynb
      environment: py
      inputs:
        - from_stage_outputs: baseline-nsys
        - from_stage_outputs: mod-nsys
      html_storage: git
      executed_ipynb_storage: git
    analyze-logs:
      kind: jupyter-notebook
      notebook_path: notebooks/analyze-logs.ipynb
      environment: py
      inputs:
        - from_stage_outputs: amip-baseline
        - from_stage_outputs: amip-mod
      outputs:
        - path: figures/sypd-time-series.png
          storage: git
      html_storage: git
      executed_ipynb_storage: git
    make-diffs:
      kind: shell-script
      environment: _system
      script_path: scripts/make-diffs.sh
      inputs:
        - ClimaCoupler.jl
        - ClimaCoupler.jl-mod
        - ClimaCore.jl
        - ClimaCore.jl-mod
        - ClimaAtmos.jl
        - ClimaAtmos.jl-mod
      outputs:
        - path: diffs
          storage: git
