owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

environments:
  clima:
    kind: slurm
    host: clima.gps.caltech.edu

pipeline:
  sequence:
    # Run all in parallel since they don't depend on each other
    - [baro-43-clima, baro-63-clima, amip-clima]
  stages:
    baro-43-clima-nsys:
      kind: sbatch
      script_path: scripts/run-slurm.sh
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=30
      args:
        - nsys
        - nsys-outputs/baroclinic-wave-moist-43
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/baroclinic-wave-moist-43.nsys-rep
    baro-63-clima-nsys:
      kind: sbatch
      script_path: scripts/run-slurm.sh
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=30
      args:
        - nsys
        - nsys-outputs/baroclinic-wave-moist-63
        - config/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - config/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/baroclinic-wave-moist-63.nsys-rep
    amip-clima-nsys:
      kind: sbatch
      script_path: scripts/run-slurm.sh
      environment: clima
      sbatch_options:
        - --gpus=1
        - --time=240
      args:
        - nsys
        - nsys-outputs/amip-target-edonly-63
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/longrun_configs/amip_target_edonly.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
        - ClimaAtmos.jl/config/longrun_configs/amip_target_edonly.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
        - Project.toml
      outputs:
        - nsys-outputs/amip-target-edonly-63.nsys-rep
