owner: petebachant
name: clima-gpu-profiling
title: CliMA GPU profiling
description: Profiling GPU performance for CliMA.
git_repo_url: https://github.com/petebachant/clima-gpu-profiling

machines: {}

environments:
  main:
    kind: julia
    path: Project.toml
  clima-ssh:
    kind: ssh
    host: clima.gps.caltech.edu
    user: $CALTECH_USERNAME
    wdir: ~/calkit/clima-gpu-profiling
    load_modules:
      - TODO
    sync_method: repo
  clima-main:
    kind: composite
    env1: clima
    env2: main
  sassy:
    kind: ssh
    host: sassy.caltech.edu
    user: $CALTECH_USERNAME
    wdir: ~/calkit/clima-gpu-profiling
    sync_method: repo
  sassy-main:
    kind: composite
    env1: sassy
    env2: main
  clima:
    kind: slurm

env_vars:
  CLIMACOMMS_DEVICE: CUDA

pipeline:
  sequence:
    # Run all in parallel since they don't depend on each other
    - [baro-43-clima, baro-63-clima, amip-clima]
  stages:
    baro-43-clima:
      kind: slurm-command
      gpus: 1
      time: 240
      command: > # TODO: Pkg.instantiate, precompile, etc., stuff here?
        nsys profile
        --start-later=true
        --capture-range=cudaProfilerApi
        --kill=none
        --trace=nvtx,mpi,cuda,osrt
        --output=nsys-outputs/baroclinic-wave-moist-43
        calkit julia -e main --
        julia --project=ClimaAtmos.jl/.buildkite
        ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        --config config/default_configs/default_config.yml
        --config config/common_configs/numerics_sphere_he30ze43.yml
        --config config/perf_configs/bm_baroclinic_wave_moist.yml
      environment: main
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
      outputs:
        - nsys-outputs/baroclinic-wave-moist-43.nsys-rep
      load_modules:
        - climacommon/2025_05_15
      env_vars:
        CLIMACOMMS_DEVICE: CUDA
      host: clima.gps.caltech.edu
      pre_run_commands:
        - julia ...
    baro-43-clima-script:
      kind: slurm-script
      script_path: scripts/run-slurm.sh
      host: clima.gps.caltech.edu
      gpus: 1
      time: 240
      args:
        - nsys-outputs/baroclinic-wave-moist-43
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      inputs:
        - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
        - ClimaAtmos.jl/config/default_configs/default_config.yml
        - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
        - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
        - ClimaAtmos.jl/src
        - ClimaCore.jl/src
      outputs:
        - nsys-outputs/baroclinic-wave-moist-43.nsys-rep
    baro-63-clima:
      kind: slurm-command
      command: >
        sbatch --gpus=1 --time 240
        nsys profile
        --start-later=true
        --capture-range=cudaProfilerApi
        --kill=none
        --trace=nvtx,mpi,cuda,osrt
        --output=nsys-outputs/baroclinic-wave-moist-63
        julia --project=.buildkite perf/benchmark_step_gpu.jl
        --config config/default_configs/default_config.yml
        --config config/common_configs/numerics_sphere_he30ze63-b.yml
        --config config/perf_configs/bm_baroclinic_wave_moist.yml
    amip-clima:
      command: >
        sbatch --gpus=1
        nsys profile
        --start-later=true
        --capture-range=cudaProfilerApi
        --kill=none
        --trace=nvtx,mpi,cuda,osrt
        --output=nsys-outputs/amip-target-edonly-63
        julia --project=.buildkite perf/benchmark_step_gpu.jl
        --config config/default_configs/default_config.yml
        --config config/common_configs/numerics_sphere_he30ze63.yml
        --config config/longrun_configs/amip_target_edonly.yml
