stages:
  baseline-nsys:
    cmd: calkit slurm batch --name baseline-nsys --environment clima 
      --dep scripts/run.jl --dep ClimaCoupler.jl/src --dep 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl --dep 
      ClimaCoupler.jl/experiments/ClimaEarth/components --dep 
      ClimaCore.jl/ext --dep ClimaCore.jl/src --dep ClimaCore.jl/lib 
      --out results/nsys/baseline.nsys-rep -s --gpus=1 -s --time=120 
      -- scripts/run-nsys.sh results/nsys/baseline 
      ClimaCoupler.jl/experiments/ClimaEarth 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl/src
      - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl/experiments/ClimaEarth/components
      - ClimaCore.jl/ext
      - ClimaCore.jl/src
      - ClimaCore.jl/lib
    outs:
      - results/nsys/baseline.nsys-rep:
          persist: true
      - .calkit/slurm/logs/baseline-nsys.out:
          cache: false
          persist: true
    desc: Automatically generated from the 'baseline-nsys' stage in 
      calkit.yaml. Changes made here will be overwritten.
  baseline-nsys-to-sqlite:
    cmd: ' bash --noprofile --norc -c "nsys export results/nsys/baseline.nsys-rep
      -t sqlite -o results/nsys/baseline.sqlite"'
    deps:
      - results/nsys/baseline.nsys-rep
    outs:
      - results/nsys/baseline.sqlite
    desc: Automatically generated from the 'baseline-nsys-to-sqlite' 
      stage in calkit.yaml. Changes made here will be overwritten.
  mod-nsys:
    cmd: calkit slurm batch --name mod-nsys --environment clima --dep 
      scripts/run.jl --dep ClimaCoupler.jl-mod/src --dep 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/components 
      --dep ClimaCore.jl-mod/ext --dep ClimaCore.jl-mod/src --dep 
      ClimaCore.jl-mod/lib --dep ClimaAtmos.jl-mod/src --out 
      results/nsys/mod.nsys-rep -s --gpus=1 -s --time=120 -- 
      scripts/run-nsys.sh results/nsys/mod 
      ClimaCoupler.jl-mod/experiments/ClimaEarth 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl-mod/src
      - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/components
      - ClimaCore.jl-mod/ext
      - ClimaCore.jl-mod/src
      - ClimaCore.jl-mod/lib
      - ClimaAtmos.jl-mod/src
    outs:
      - results/nsys/mod.nsys-rep:
          persist: true
      - .calkit/slurm/logs/mod-nsys.out:
          cache: false
          persist: true
    desc: Automatically generated from the 'mod-nsys' stage in 
      calkit.yaml. Changes made here will be overwritten.
  mod-nsys-to-sqlite:
    cmd: ' bash --noprofile --norc -c "nsys export results/nsys/mod.nsys-rep
      -t sqlite -o results/nsys/mod.sqlite"'
    deps:
      - results/nsys/mod.nsys-rep
    outs:
      - results/nsys/mod.sqlite
    desc: Automatically generated from the 'mod-nsys-to-sqlite' stage 
      in calkit.yaml. Changes made here will be overwritten.
  baseline-ncu:
    cmd: calkit slurm batch --name baseline-ncu --environment clima 
      --dep scripts/run.jl --dep ClimaCoupler.jl/src --dep 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl --dep 
      ClimaCoupler.jl/experiments/ClimaEarth/components --dep 
      ClimaCore.jl/ext --dep ClimaCore.jl/src --dep ClimaCore.jl/lib 
      --out results/ncu/baseline.ncu-rep -s --gpus=1 -s --time=120 -- 
      scripts/run-ncu.sh results/ncu/baseline --kernel-name 
      run_field_matrix_solver__FILE_ClimaCore_jl_src_MatrixFields_field_matrix_solver_jl_L354
      --project ClimaCoupler.jl/experiments/ClimaEarth --config 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --launch-count 6
    deps:
      - scripts/run-ncu.sh
      - scripts/run.jl
      - ClimaCoupler.jl/src
      - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl/experiments/ClimaEarth/components
      - ClimaCore.jl/ext
      - ClimaCore.jl/src
      - ClimaCore.jl/lib
    outs:
      - results/ncu/baseline.ncu-rep:
          persist: true
      - .calkit/slurm/logs/baseline-ncu.out:
          cache: false
          persist: true
    desc: Automatically generated from the 'baseline-ncu' stage in 
      calkit.yaml. Changes made here will be overwritten.
  baseline-ncu-details-csv:
    cmd: ' bash --noprofile --norc -c "ncu --csv -i results/ncu/baseline.ncu-rep
      --page details --log-file results/ncu/baseline-details.csv"'
    deps:
      - results/ncu/baseline.ncu-rep
    outs:
      - results/ncu/baseline-details.csv:
          cache: false
          persist: false
    desc: Automatically generated from the 'baseline-ncu-details-csv' 
      stage in calkit.yaml. Changes made here will be overwritten.
  mod-ncu:
    cmd: calkit slurm batch --name mod-ncu --environment clima --dep 
      scripts/run.jl --dep ClimaCoupler.jl-mod/src --dep 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/components 
      --dep ClimaCore.jl-mod/ext --dep ClimaCore.jl-mod/src --dep 
      ClimaCore.jl-mod/lib --out results/ncu/mod.ncu-rep -s --gpus=1 
      -s --time=120 -- scripts/run-ncu.sh results/ncu/mod 
      --kernel-name 
      run_field_matrix_solver__FILE_ClimaCore_jl_mod_src_MatrixFields_field_matrix_solver_jl_L419
      --project ClimaCoupler.jl-mod/experiments/ClimaEarth --config 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --launch-count 6
    deps:
      - scripts/run-ncu.sh
      - scripts/run.jl
      - ClimaCoupler.jl-mod/src
      - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/components
      - ClimaCore.jl-mod/ext
      - ClimaCore.jl-mod/src
      - ClimaCore.jl-mod/lib
    outs:
      - results/ncu/mod.ncu-rep:
          persist: true
      - .calkit/slurm/logs/mod-ncu.out:
          cache: false
          persist: true
    desc: Automatically generated from the 'mod-ncu' stage in 
      calkit.yaml. Changes made here will be overwritten.
  mod-ncu-details-csv:
    cmd: ' bash --noprofile --norc -c "ncu --csv -i results/ncu/mod.ncu-rep
      --page details --log-file results/ncu/mod-details.csv"'
    deps:
      - results/ncu/mod.ncu-rep
    outs:
      - results/ncu/mod-details.csv:
          cache: false
          persist: false
    desc: Automatically generated from the 'mod-ncu-details-csv' stage
      in calkit.yaml. Changes made here will be overwritten.
  amip-baseline:
    cmd: calkit slurm batch --name amip-baseline --environment clima 
      --dep ClimaCoupler.jl/experiments/ClimaEarth/run_amip.jl --dep 
      ClimaCoupler.jl/src --dep 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl --dep 
      ClimaCoupler.jl/experiments/ClimaEarth/components --dep 
      ClimaCore.jl/ext --dep ClimaCore.jl/src --dep ClimaCore.jl/lib 
      --dep ClimaAtmos.jl/src --dep ClimaAtmos.jl/toml -s --gpus=1 -s 
      --time=240 -- scripts/run-julia-script.sh 
      --project=ClimaCoupler.jl/experiments/ClimaEarth 
      ClimaCoupler.jl/experiments/ClimaEarth/run_amip.jl --config_file
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --job_id gpu_amip_progedmf_1M_land_he16_baseline
    deps:
      - scripts/run-julia-script.sh
      - ClimaCoupler.jl/experiments/ClimaEarth/run_amip.jl
      - ClimaCoupler.jl/src
      - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl/experiments/ClimaEarth/components
      - ClimaCore.jl/ext
      - ClimaCore.jl/src
      - ClimaCore.jl/lib
      - ClimaAtmos.jl/src
      - ClimaAtmos.jl/toml
    outs:
      - .calkit/slurm/logs/amip-baseline.out:
          cache: false
          persist: true
    desc: Automatically generated from the 'amip-baseline' stage in 
      calkit.yaml. Changes made here will be overwritten.
  amip-mod:
    cmd: calkit slurm batch --name amip-mod --environment clima --dep 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/run_amip.jl --dep 
      ClimaCoupler.jl-mod/src --dep 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/components 
      --dep ClimaCore.jl-mod/ext --dep ClimaCore.jl-mod/src --dep 
      ClimaCore.jl-mod/lib --dep ClimaAtmos.jl-mod/src --dep 
      ClimaAtmos.jl-mod/toml -s --gpus=1 -s --time=240 -- 
      scripts/run-julia-script.sh 
      --project=ClimaCoupler.jl-mod/experiments/ClimaEarth 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/run_amip.jl 
      --config_file 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --job_id gpu_amip_progedmf_1M_land_he16_mod
    deps:
      - scripts/run-julia-script.sh
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/run_amip.jl
      - ClimaCoupler.jl-mod/src
      - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/components
      - ClimaCore.jl-mod/ext
      - ClimaCore.jl-mod/src
      - ClimaCore.jl-mod/lib
      - ClimaAtmos.jl-mod/src
      - ClimaAtmos.jl-mod/toml
    outs:
      - .calkit/slurm/logs/amip-mod.out:
          cache: false
          persist: true
    desc: Automatically generated from the 'amip-mod' stage in 
      calkit.yaml. Changes made here will be overwritten.
  summarize:
    cmd: calkit xenv -n py --no-check -- python scripts/summarize.py
    deps:
      - scripts/summarize.py
      - results/nsys/baseline.sqlite
      - results/nsys/mod.sqlite
      - .calkit/env-locks/py
      - .calkit/slurm/logs/amip-baseline.out
      - .calkit/slurm/logs/amip-mod.out
    outs:
      - results/summary.json:
          cache: false
          persist: false
    desc: Automatically generated from the 'summarize' stage in 
      calkit.yaml. Changes made here will be overwritten.
