stages:
  baro-43-clima-nsys:
    cmd: calkit slurm batch --name baro-43-clima-nsys --environment 
      clima --dep ClimaAtmos.jl/perf/benchmark_step_gpu.jl --dep 
      ClimaAtmos.jl/config/default_configs/default_config.yml --dep 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
      --dep 
      ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml 
      --dep ClimaAtmos.jl/src --dep ClimaCore.jl/src --dep 
      Project.toml --out 
      nsys-outputs/baroclinic-wave-moist-43.nsys-rep -s --gpus=1 -s 
      --time=30 -- scripts/run-nsys-clima.sh 
      nsys-outputs/baroclinic-wave-moist-43 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
      ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
    deps:
      - scripts/run-nsys-clima.sh
      - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
      - ClimaAtmos.jl/config/default_configs/default_config.yml
      - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze43.yml
      - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      - ClimaAtmos.jl/src
      - ClimaCore.jl/src
      - Project.toml
    outs:
      - nsys-outputs/baroclinic-wave-moist-43.nsys-rep:
          persist: true
    desc: Automatically generated from the 'baro-43-clima-nsys' stage 
      in calkit.yaml. Changes made here will be overwritten.
  baro-63-clima-nsys:
    cmd: calkit slurm batch --name baro-63-clima-nsys --environment 
      clima --dep ClimaAtmos.jl/perf/benchmark_step_gpu.jl --dep 
      ClimaAtmos.jl/config/default_configs/default_config.yml --dep 
      config/numerics_sphere_he30ze63.yml --dep 
      ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml 
      --dep ClimaAtmos.jl/src --dep ClimaCore.jl/src --dep 
      Project.toml --out 
      nsys-outputs/baroclinic-wave-moist-63.nsys-rep -s --gpus=1 -s 
      --time=60 -- scripts/run-nsys-clima.sh 
      nsys-outputs/baroclinic-wave-moist-63 
      config/numerics_sphere_he30ze63.yml 
      ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
    deps:
      - scripts/run-nsys-clima.sh
      - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
      - ClimaAtmos.jl/config/default_configs/default_config.yml
      - config/numerics_sphere_he30ze63.yml
      - ClimaAtmos.jl/config/perf_configs/bm_baroclinic_wave_moist.yml
      - ClimaAtmos.jl/src
      - ClimaCore.jl/src
      - Project.toml
    outs:
      - nsys-outputs/baroclinic-wave-moist-63.nsys-rep:
          persist: true
    desc: Automatically generated from the 'baro-63-clima-nsys' stage 
      in calkit.yaml. Changes made here will be overwritten.
  amip-clima-nsys:
    cmd: calkit slurm batch --name amip-clima-nsys --environment clima
      --dep ClimaAtmos.jl/perf/benchmark_step_gpu.jl --dep 
      ClimaAtmos.jl/config/default_configs/default_config.yml --dep 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      --dep config/amip_target_edonly.yml --dep 
      ClimaAtmos.jl/toml/longrun_aquaplanet.toml --dep 
      ClimaAtmos.jl/src --dep ClimaCore.jl/src --dep Project.toml 
      --out nsys-outputs/amip-target-edonly-63.nsys-rep -s --gpus=1 -s
      --time=240 -- scripts/run-nsys-clima.sh 
      nsys-outputs/amip-target-edonly-63 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      config/amip_target_edonly.yml
    deps:
      - scripts/run-nsys-clima.sh
      - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
      - ClimaAtmos.jl/config/default_configs/default_config.yml
      - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      - config/amip_target_edonly.yml
      - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
      - ClimaAtmos.jl/src
      - ClimaCore.jl/src
      - Project.toml
    outs:
      - nsys-outputs/amip-target-edonly-63.nsys-rep:
          persist: true
    desc: Automatically generated from the 'amip-clima-nsys' stage in 
      calkit.yaml. Changes made here will be overwritten.
  amip-clima-ncu:
    cmd: calkit slurm batch --name amip-clima-ncu --environment clima 
      --dep ClimaAtmos.jl/perf/benchmark_step_gpu.jl --dep 
      ClimaAtmos.jl/config/default_configs/default_config.yml --dep 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      --dep config/amip_target_edonly.yml --dep 
      ClimaAtmos.jl/toml/longrun_aquaplanet.toml --dep 
      ClimaAtmos.jl/src --dep ClimaCore.jl/src --dep Project.toml 
      --out ncu-outputs/amip-target-edonly-63.ncu-rep -s --gpus=1 -s 
      --time=240 -- scripts/run-ncu-clima.sh 
      ncu-outputs/amip-target-edonly-63 --config 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      --config config/amip_target_edonly.yml --kernel-name 
      copyto_stencil_kernel_ --launch-skip 0 --launch-count 20
    deps:
      - scripts/run-ncu-clima.sh
      - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
      - ClimaAtmos.jl/config/default_configs/default_config.yml
      - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      - config/amip_target_edonly.yml
      - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
      - ClimaAtmos.jl/src
      - ClimaCore.jl/src
      - Project.toml
    outs:
      - ncu-outputs/amip-target-edonly-63.ncu-rep:
          persist: true
    desc: Automatically generated from the 'amip-clima-ncu' stage in 
      calkit.yaml. Changes made here will be overwritten.
  amip-ncu-update-jacobian:
    cmd: calkit slurm batch --name amip-ncu-update-jacobian 
      --environment clima --dep 
      ClimaAtmos.jl/perf/benchmark_step_gpu.jl --dep 
      ClimaAtmos.jl/perf/common.jl --dep 
      ClimaAtmos.jl/config/default_configs/default_config.yml --dep 
      ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      --dep config/amip_target_edonly.yml --dep 
      ClimaAtmos.jl/toml/longrun_aquaplanet.toml --dep 
      ClimaAtmos.jl/src --dep ClimaCore.jl/src --dep Project.toml 
      --out ncu-outputs/amip-update-jacobian-kernel.ncu-rep -s 
      --gpus=1 -s --time=240 -- 
      scripts/run-ncu-amip-update-jacobian.sh
    deps:
      - scripts/run-ncu-amip-update-jacobian.sh
      - ClimaAtmos.jl/perf/benchmark_step_gpu.jl
      - ClimaAtmos.jl/perf/common.jl
      - ClimaAtmos.jl/config/default_configs/default_config.yml
      - ClimaAtmos.jl/config/common_configs/numerics_sphere_he30ze63.yml
      - config/amip_target_edonly.yml
      - ClimaAtmos.jl/toml/longrun_aquaplanet.toml
      - ClimaAtmos.jl/src
      - ClimaCore.jl/src
      - Project.toml
    outs:
      - ncu-outputs/amip-update-jacobian-kernel.ncu-rep:
          persist: true
    desc: Automatically generated from the 'amip-ncu-update-jacobian' 
      stage in calkit.yaml. Changes made here will be overwritten.
