stages:
  baseline-nsys:
    cmd: calkit slurm batch --name baseline-nsys --environment clima 
      --dep scripts/run.jl --dep ClimaCoupler.jl/src --dep 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      --dep ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl --dep 
      ClimaCoupler.jl/experiments/ClimaEarth/components --dep 
      ClimaCore.jl/ext --dep ClimaCore.jl/src --dep ClimaCore.jl/lib 
      --out results/nsys/baseline.nsys-rep -s --gpus=1 -s --time=120 
      -- scripts/run-nsys.sh results/nsys/baseline 
      ClimaCoupler.jl/experiments/ClimaEarth 
      ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl/src
      - ClimaCoupler.jl/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl/experiments/ClimaEarth/components
      - ClimaCore.jl/ext
      - ClimaCore.jl/src
      - ClimaCore.jl/lib
    outs:
      - results/nsys/baseline.nsys-rep:
          persist: true
    desc: Automatically generated from the 'baseline-nsys' stage in 
      calkit.yaml. Changes made here will be overwritten.
  baseline-nsys-to-sqlite:
    cmd: ' bash --noprofile --norc -c "nsys export results/nsys/baseline.nsys-rep
      -t sqlite -o results/nsys/baseline.sqlite"'
    deps:
      - results/nsys/baseline.nsys-rep
    outs:
      - results/nsys/baseline.sqlite
    desc: Automatically generated from the 'baseline-nsys-to-sqlite' 
      stage in calkit.yaml. Changes made here will be overwritten.
  mod-nsys:
    cmd: calkit slurm batch --name mod-nsys --environment clima --dep 
      scripts/run.jl --dep ClimaCoupler.jl-mod/src --dep 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      --dep 
      ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl 
      --dep ClimaCoupler.jl-mod/experiments/ClimaEarth/components 
      --dep ClimaCore.jl-mod/ext --dep ClimaCore.jl-mod/src --dep 
      ClimaCore.jl-mod/lib --out results/nsys/mod.nsys-rep -s --gpus=1
      -s --time=120 -- scripts/run-nsys.sh results/nsys/mod 
      ClimaCoupler.jl-mod/experiments/ClimaEarth 
      ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
    deps:
      - scripts/run-nsys.sh
      - scripts/run.jl
      - ClimaCoupler.jl-mod/src
      - ClimaCoupler.jl-mod/config/benchmark_configs/amip_progedmf_1m_land_he16.yml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/Manifest-v1.11.toml
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/setup_run.jl
      - ClimaCoupler.jl-mod/experiments/ClimaEarth/components
      - ClimaCore.jl-mod/ext
      - ClimaCore.jl-mod/src
      - ClimaCore.jl-mod/lib
    outs:
      - results/nsys/mod.nsys-rep:
          persist: true
    desc: Automatically generated from the 'mod-nsys' stage in 
      calkit.yaml. Changes made here will be overwritten.
  mod-nsys-to-sqlite:
    cmd: ' bash --noprofile --norc -c "nsys export results/nsys/mod.nsys-rep
      -t sqlite -o results/nsys/mod.sqlite"'
    deps:
      - results/nsys/mod.nsys-rep
    outs:
      - results/nsys/mod.sqlite
    desc: Automatically generated from the 'mod-nsys-to-sqlite' stage 
      in calkit.yaml. Changes made here will be overwritten.
