stages:
  baro-43-clima:
    cmd: >
      calkit slurm run-stage --name baro-43-clima
      --out nsys-reports/baro-43-clima.nsys-rep
      --load-module climacommon/2025_05_15
      --env-var CLIMACOMMS_DEVICE=CUDA
      --
      echo sup > lol.txt
    deps:
      - sup
    outs:
      - .calkit/jobs/slurm/baro-43-clima.yaml:
          cache: false
          persist: true
  # TODO: Do we have one stage that awaits all jobs?
  _slurm-await-baro-43-clima:
    cmd: calkit slurm await-stage --name baro-43-clima
    deps:
      - .calkit/jobs/slurm/baro-43-clima.yaml
    outs:
      - nsys-reports/baro-43-clima.nsys-rep:
          persist: true
  # How to put dependencies between jobs?
  baro-43-clima-post:
    cmd: calkit slurm run-stage --name baro-43-clima-post -o postproc
    deps:
      - nsys-reports/baro-43-clima.nsys-rep
    outs:
      - .calkit/jobs/slurm/baro-43-clima-post.yaml:
          cache: false
          persist: true
  _slurm-await-baro-43-clima-post:
    cmd: calkit slurm await-stage --name baro-43-clima-post
    deps:
      - .calkit/jobs/slurm/baro-43-clima-post.yaml
    outs:
      - postproc:
          persist: true
    always_changed: true # Always check to see if there's a job to await
