"""Prove a clone of this commit hashes the same bytes this working tree does.

DVC hashes the working tree. A fresh clone gets what Git stored. Those differ in
exactly two ways, and both are silent -- `git status` is clean either way:

  not stored    A file inside a dependency lives only on this machine, so the
                clone hashes a different set.
  rewritten     A clean filter changed the bytes on the way into Git, so the
                clone materializes something else. nbstripout does this.

Either one pins a stage's recorded hash to the machine that ran it, and the
stage then reads as stale on every other clone, forever.

Checked per dependency, so it answers the only question that matters about a
tag: will `calkit status` be clean for someone else?
"""

import os
import subprocess
import sys

import yaml


def run(args, **kw):
    return subprocess.run(args, capture_output=True, text=True, **kw).stdout


def repo_of(path: str) -> tuple[str, str]:
    """Split a path into the repo holding it and the path within that repo."""
    top = path.split("/")[0]
    if os.path.exists(os.path.join(top, ".git")):
        return top, path[len(top) + 1 :]
    return ".", path


def check(repo: str, rel: str) -> list[str]:
    """Files under ``rel`` whose stored bytes differ from the working tree."""
    listed = run(["git", "-C", repo, "ls-files", "--", rel]).splitlines()
    problems = []
    for name in listed:
        full = os.path.join(repo, name) if repo != "." else name
        if not os.path.exists(full):
            continue
        # Hash the same bytes twice, once through the clean filter and once
        # not. Comparing against the index instead would flag any file merely
        # edited since it was staged, which says nothing about a filter.
        filtered = run(["git", "-C", repo, "hash-object", "--", name]).strip()
        raw = run(
            ["git", "-C", repo, "hash-object", "--no-filters", "--", name]
        ).strip()
        if filtered and raw and filtered != raw:
            problems.append(f"rewritten by a clean filter: {full}")
    return problems


CLEANED = ".calkit/notebooks/cleaned/"


def main() -> int:
    lock = yaml.safe_load(open("dvc.lock"))
    produced = {o["path"] for st in lock["stages"].values() for o in st.get("outs", [])}
    deps = {d["path"] for st in lock["stages"].values() for d in st.get("deps", [])}

    problems = []
    for dep in sorted(deps):
        if dep in produced or any(
            dep.startswith(p.rstrip("/") + "/") for p in produced
        ):
            continue  # comes from `dvc pull`, not from Git
        if not os.path.exists(dep):
            continue
        repo, rel = repo_of(dep)
        problems += check(repo, rel)
        if dep.startswith(CLEANED):
            # Regenerated by `calkit status` from the source notebook, so what
            # has to match across clones is that source -- and it is not itself
            # a dependency, so nothing else here would look at it.
            src = dep[len(CLEANED) :]
            if not os.path.exists(src):
                problems.append(f"cleaned notebook has no source: {dep}")
            else:
                problems += check(*repo_of(src))
            continue
        if os.path.isfile(dep):
            r = subprocess.run(
                ["git", "-C", repo, "ls-files", "--error-unmatch", "--", rel],
                capture_output=True,
            )
            if r.returncode:
                problems.append(f"not stored in Git: {dep}")

    for p in problems:
        print(f"FAIL {p}")
    if not problems:
        print(f"ok   {len(deps)} dependencies: a clone hashes identical bytes")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
