"""Snapshot the stacked-treatment measurement.

results/summary.json holds whichever arm pair ran last, so the combined figure
cannot be cited from it. This writes the small derived numbers, with the two
single-treatment measurements read out of Git rather than typed, so the
composition claim is checkable.
"""

import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

OUT = Path("results/combined-stack.json")

# The two treatments measured one at a time, each against its own baseline.
SINGLES = {
    "fold": ("4a2424b", "the microphysics parameter fold in ClimaAtmos"),
    "radiation": ("892054c27", "the fused longwave and shortwave radiation solves"),
}
LOG = Path(".calkit/scheduler/logs")
STEP_RE = re.compile(r"Walltime per coupling step: ([0-9.]+)")


def git(*args):
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout


def sypd_at(ref):
    s = json.loads(git("show", f"{ref}:results/summary.json"))
    return s["baseline"]["sypd"], s["mod"]["sypd"]


def per_step(name):
    hits = STEP_RE.findall((LOG / f"{name}.out").read_text(errors="replace"))
    assert hits, f"no walltime per coupling step in {name}.out"
    return float(hits[-1])


def pct(old, new):
    return round(100.0 * (new - old) / old, 2)


def measured_on():
    """The date of the run being snapshotted, from the log it reads."""
    newest = max((LOG / f"amip-{a}.out").stat().st_mtime for a in ("baseline", "mod"))
    return datetime.fromtimestamp(newest).date().isoformat()


def prior_snapshot():
    """The snapshot this one supersedes, read out of Git rather than typed.

    A re-measurement on a different implementation of the same treatment is
    only comparable if the two figures sit side by side, so the file carries
    what it replaced and the delta between them.
    """
    ref = git("log", "-1", "--format=%H", "--", str(OUT)).strip()
    if not ref:
        return None
    try:
        was = json.loads(git("show", f"{ref}:{OUT}"))
    except subprocess.CalledProcessError:
        return None
    return {
        "commit": ref,
        "measured": was.get("provenance", {}).get("measured"),
        "rrtmgp_mod_ref": was.get("provenance", {})
        .get("submodules", {})
        .get("RRTMGP.jl-mod", {})
        .get("ref"),
        "baseline_sypd": was["combined"]["baseline_sypd"],
        "mod_sypd": was["combined"]["mod_sypd"],
        "sypd_change_pct": was["combined"]["sypd_change_pct"],
        "s_per_step_change_pct": was["combined"]["s_per_step_change_pct"],
    }


def main():
    summary = json.loads(Path("results/summary.json").read_text())
    prior = prior_snapshot()
    shares = json.loads(Path("results/kernel-shares.json").read_text())
    fold = json.loads(Path("results/param-fold.json").read_text())
    treatment = json.loads(Path("results/treatment.json").read_text())

    bs, ms = summary["baseline"]["sypd"], summary["mod"]["sypd"]
    bstep, mstep = per_step("amip-baseline"), per_step("amip-mod")
    if (ms > bs) != (mstep < bstep):
        sys.exit(
            f"SYPD and per-step walltime moved the same way "
            f"({bs}->{ms} SYPD, {bstep}->{mstep} s): the timestep changed"
        )

    dev = fold["device_total"]
    # Radiation's share is of each arm's own total, so the saving has to be
    # taken in milliseconds before it can be compared to the fold's.
    rad_b = dev["baseline_ms"] * shares["baseline"]["radiation_pct"] / 100.0
    rad_m = dev["mod_ms"] * shares["mod"]["radiation_pct"] / 100.0
    rad_saved = rad_b - rad_m
    fold_saved = fold["fold_attributable"]["ms_saved"]

    singles = {}
    factors = 1.0
    for name, (ref, what) in SINGLES.items():
        b, m = sypd_at(ref)
        singles[name] = {
            "commit": ref,
            "treatment": what,
            "baseline_sypd": b,
            "mod_sypd": m,
            "sypd_change_pct": pct(b, m),
            "speedup_factor": round(m / b, 5),
            # The per-step figure experiments.csv reports, recovered from the
            # SYPD ratio, which needs no assumption about dt.
            "s_per_step_change_pct": round(100.0 * (b / m - 1.0), 2),
        }
        factors *= m / b
    combined_factor = ms / bs

    out = {
        "provenance": {
            "source_commit": git("rev-parse", "HEAD").strip(),
            "measured": measured_on(),
            "treatments_stacked": sorted(SINGLES),
            "why_kept": (
                "results/summary.json is regenerated by every run, so the "
                "combined figure has to be snapshotted to be citable. The "
                "single-treatment figures are read from Git at the commits "
                "that measured them."
            ),
            "submodules": treatment.get("submodules", {}),
            "reproducible": treatment.get("reproducible"),
        },
        "combined": {
            "baseline_sypd": bs,
            "mod_sypd": ms,
            "sypd_change_pct": pct(bs, ms),
            "baseline_s_per_step": bstep,
            "mod_s_per_step": mstep,
            "s_per_step_change_pct": pct(bstep, mstep),
            "speedup_factor": round(combined_factor, 5),
        },
        "singles": singles,
        "prior": prior,
        "composition": {
            "product_of_single_factors": round(factors, 5),
            "measured_factor": round(combined_factor, 5),
            "measured_vs_product_pct": pct(factors, combined_factor),
            "sum_of_single_per_step_pct": None,  # filled below
            "note": (
                "Each single was measured against its own baseline, so this "
                "compares speedup FACTORS rather than percentage points. A "
                "measured factor at the product means the two treatments "
                "compose; the comparison is not a controlled one, because the "
                "baselines differ and the stack moved between them."
            ),
        },
        # Carried here so the answer can template them: kernel-shares.json is
        # regenerated by every run, so a figure cited from it would drift.
        "shares": {
            "baseline_radiation_pct": shares["baseline"]["radiation_pct"],
            "mod_radiation_pct": shares["mod"]["radiation_pct"],
            "baseline_microphysics_hot_pct": shares["baseline"][
                "microphysics_hot_kernel_pct"
            ],
            "mod_microphysics_hot_pct": shares["mod"]["microphysics_hot_kernel_pct"],
        },
        "device": {
            "baseline_ms": dev["baseline_ms"],
            "mod_ms": dev["mod_ms"],
            "change_pct": dev["change_pct"],
            "ms_saved": dev["ms_saved"],
            "radiation_ms_saved": round(rad_saved, 1),
            "fold_ms_saved": fold_saved,
            "radiation_share_of_saving_pct": round(
                100.0 * rad_saved / dev["ms_saved"], 1
            ),
            "fold_share_of_saving_pct": round(
                100.0 * fold_saved / dev["ms_saved"], 1
            ),
            "unattributed_ms": round(dev["ms_saved"] - rad_saved - fold_saved, 1),
        },
    }
    if prior is not None:
        # Whether the re-measurement reproduced the earlier one is the question
        # that decides if the pinned single-treatment figures still transfer.
        out["prior"]["mod_sypd_change_pct"] = pct(prior["mod_sypd"], ms)
    out["composition"]["sum_of_single_per_step_pct"] = round(
        sum(v["s_per_step_change_pct"] for v in singles.values()), 2
    )
    OUT.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n")

    c, k = out["combined"], out["device"]
    print(f"combined: {bs:.5f} -> {ms:.5f} SYPD ({c['sypd_change_pct']:+.2f}%), "
          f"{bstep:.5f} -> {mstep:.5f} s/step ({c['s_per_step_change_pct']:+.2f}%)")
    for name, v in singles.items():
        print(f"  {name:10s} {v['sypd_change_pct']:+6.2f}% SYPD / "
              f"{v['s_per_step_change_pct']:+6.2f}% per step, alone at {v['commit']}")
    p = out["composition"]
    print(f"composition: product {p['product_of_single_factors']:.5f} vs measured "
          f"{p['measured_factor']:.5f} ({p['measured_vs_product_pct']:+.2f}%); "
          f"per step {p['sum_of_single_per_step_pct']:+.2f}% summed vs "
          f"{c['s_per_step_change_pct']:+.2f}% measured")
    print(f"device: {k['ms_saved']:.1f} ms saved = {k['radiation_ms_saved']:.1f} radiation "
          f"+ {k['fold_ms_saved']:.1f} fold + {k['unattributed_ms']:.1f} unattributed")
    if prior is not None:
        pr = out["prior"]
        print(f"prior: {pr['measured']} on {pr['rrtmgp_mod_ref']} gave "
              f"{pr['mod_sypd']:.5f} SYPD; this run {ms:.5f} "
              f"({pr['mod_sypd_change_pct']:+.2f}%)")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
